[project]
name = "sxp_wrapper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [ ]

[project.scripts]
hello = "sxp_wrapper:main"

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"
