[project]
name = "sxp_wrapper"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
 "slides-xp>=0.0.10",
]

[build-system]
requires = ["uv_build>=0.9.0,<0.10.0"]
build-backend = "uv_build"
